### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danielschmitz** [danielschmitz/svelte-sapper-bulma-crud#1]
**Application**

- [ ] Enable HMR in Webpack

**Category**

- [x] Read All Categories
- [x] Create Category
- [x] Update Category
- [x] Delete Category

**Product**
- [x] Read All 
- [x] Create 
- [x] Update 
- [x] Delete 
- [x] Component: Selection with categories
- [x] Component: Selection with suppliers

**Suplier**

- [ ] Read All 
- [ ] Create 
- [ ] Update 
- [ ] Delete 

**Employee**

- [ ] Read All 
- [ ] Create 
- [ ] Update 
- [ ] Delete

**Comment by DzunN86** [comment]
if I've install bulma on sapper, where should I call the bulma it's self ?

**Comment by DzunN86** [comment]
How do I setup Axios in svelte ?

**Comment by danielschmitz** [comment]
> How do I setup Axios in svelte ?

here: https://github.com/danielschmitz/svelte-sapper-bulma-crud/blob/master/src/http.js

**Comment by DzunN86** [comment]
for getting data do you axios method too?

**Comment by danielschmitz** [comment]
> for getting data do you axios method too?

yeap.

example:

```js
import http from "../http";

async function onDeleteClick(item) {
    product = item;
    if (confirm(`Delete "${product.name}"?`)) {
      await http.delete(`/products/${product.id}`);
      products = getProducts();
    }
  }
```
